### ISSUE TITLE
[Bug] "CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):   Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules are removed."

### ISSUE THREAD

**Issue by AmericaPacific42** [KhronosGroup/glslang#3349]
[code]~/Vulkan-Hpp $ cmake --build .
--  Found clang-format version <16.0.6>.
--  Using .clang-format version 15.
-- Including X11 support
CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/CMakeLists.txt:315 (find_host_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/StandAlone/CMakeLists.txt:34 (find_host_package)[/code]

**Comment by arcady-lunarg** [comment]
Hi, could you please confirm which version of glslang you are using? We recently removed these calls, in commit  5793fbd6248921296c0b3166e0a427abf9e37211.

**Comment by AmericaPacific42** [comment]
`git pull` = solution

**Comment by AmericaPacific42** [comment]
`~/Vulkan-Hpp/glslang $ git checkout main
^[[APrevious HEAD position was bffcf209 Merge pull request #2962 from James2022-rgb/feature/c_interface_opsource_support
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
~/Vulkan-Hpp/glslang $ git pull
Already up to date.
~/Vulkan-Hpp/glslang $ cd ../
~/Vulkan-Hpp $ cmake -DVULKAN_HPP_SAMPLES_BUILD=ON -DVULKAN_HPP_TESTS_BUILD=ON -DALLOW_EXTERNAL_SPIRV_TOOLS=ON
--  Found clang-format version <17.0.2>.
--  Using .clang-format version 15.
-- Including X11 support
CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/CMakeLists.txt:315 (find_host_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Google Mock was not found - tests based on that will not build
-- spirv-tools not linked - illegal SPIRV may be generated for HLSL
CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  glslang/StandAlone/CMakeLists.txt:34 (find_host_package)`

**Comment by juan-lunarg** [comment]
>  CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):

I'm unable to reproduce the issue. And looking at the CI log I can't find this issue either.

<details>

```
Run cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug
-- The C compiler identification is Clang 14.0.0
-- The CXX compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /opt/hostedtoolcache/Python/3.7.17/x64/bin/python3.7 (found version "3.7.17") found components: Interpreter 
CMake Deprecation Warning at External/googletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at External/googletest/googlemock/CMakeLists.txt:45 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at External/googletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Warning (dev) at External/googletest/googletest/cmake/internal_utils.cmake:247 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  External/googletest/googletest/CMakeLists.txt:91 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /opt/hostedtoolcache/Python/3.7.17/x64/bin/python (found version "3.7.17") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- optimizer enabled
-- Google Mock found - building tests
-- Configuring done (3.0s)
-- Generating done (0.1s)
-- Build files have been written to: /home/runner/work/glslang/glslang/buil
```

</details>

There are warnings but they are coming from googletest not glslang. You most definitely aren't using ToT main. 

Looking at your logs ``~/Vulkan-Hpp/glslang` you are developing in Vulkan-Hpp via a submodule.

Please review the following stackoverflow:
https://stackoverflow.com/questions/33714063/how-to-update-submodules-in-git

**Comment by ETERNALBLUEbullrun** [comment]
Ran `~/Vulkan-Hpp $ git submodule update --recursive`
`~/Vulkan-Hpp $ git submodule update --recursive --remote` but no solution.

**Comment by juan-lunarg** [comment]
Try `git submodule update --remote --merge` it requires git 1.8 though.

**Comment by AmericaPacific42** [comment]
~/Vulkan-Hpp $ cmake --help-policy CMP0148
... The ``FindPythonInterp`` and ``FindPythonLibs`` modules are removed.

These modules have been deprecated since CMake 3.12.
... Projects using the ``FindPythonInterp`` and/or ``FindPythonLibs``
modules should be updated to use one of their replacements:

* ``FindPython3``
* ``FindPython2``
* ``FindPython``

The ``OLD`` behavior of this policy is for ``find_package(PythonInterp)``
and ``find_package(PythonLibs)`` to load the deprecated modules.  The ``NEW``
behavior is for uses of the modules to fail as if they do not exist.

This policy was introduced in CMake version 3.27.  CMake version
3.27.7 warns when the policy is not set and uses ``OLD`` behavior.
Use the ``cmake_policy()`` command to set it to ``OLD`` or ``NEW``
explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.`

**Comment by AmericaPacific42** [comment]
`~/Vulkan-Hpp/glslang $ git checkout main
^[[APrevious HEAD position was https://github.com/KhronosGroup/glslang/commit/bffcf209cb67f718bd8faafd43d0379f943c116f Merge pull request https://github.com/KhronosGroup/glslang/pull/2962 from James2022-rgb/feature/c_interface_opsource_support
Switched to branch 'main'
Your branch is up to date with 'origin/main'.`
Not outdated.

`CMake Warning (dev) at glslang/CMakeLists.txt:251 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.`
Error from glslang, not from Google.

**Comment by juan-lunarg** [comment]
Yes I'm aware. I fixed this a while ago.

https://github.com/KhronosGroup/glslang/pull/3241

**Comment by juan-lunarg** [comment]
As a sanity check I just did a fresh clone of `glslang`. I don't see any warnings. I also double checked the CI in the validation layers which consumes glslang as a dependency for testing and didn't see it there either.

```
PS D:\projects\glslang> cmake --version
cmake version 3.27.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).
PS D:\projects\glslang> cmake -S . -B build --fresh
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.37.32822.0
-- The CXX compiler identification is MSVC 19.37.32822.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Debug
-- Found Python3: C:/Users/juan/AppData/Local/Programs/Python/Python311/python.exe (found version "3.11.3") found components: Interpreter
-- Google Mock was not found - tests based on that will not build
-- optimizer enabled
-- Configuring done (4.0s)
-- Generating done (3.1s)
-- Build files have been written to: D:/projects/glslang/build
```

**Comment by AmericaPacific42** [comment]
> Yes I'm aware. I fixed this a while ago.
> 
> #3241

Just ran "git pull" and still broken.
Does it only work in some weird development branch?

**Comment by juan-lunarg** [comment]
>  Does it only work in some weird development branch?

No I did a fresh clone of glslang and it's fixed on main. Please try doing a fresh clone of glslang.

**Comment by arcady-lunarg** [comment]
Looks like this is working as expected on `main`.
